/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "string_check.check" instead.
 */

#include <check.h>
#include <errno.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>

#include "s21_string.h"

/// strpbrk

START_TEST(empty_s1) {
  char s1[] = "";
  char s2[] = "Hello everyone123";

  ck_assert_pstr_eq(s21_strpbrk(s1, s2), strpbrk(s1, s2));
}
END_TEST

START_TEST(some_s1_in_s2) {
  char s1[] = "hellello";
  char s2[] = "el";

  ck_assert_pstr_eq(s21_strpbrk(s1, s2), strpbrk(s1, s2));
}
END_TEST

START_TEST(empty_s1s2) {
  char s1[] = "";
  char s2[] = "";

  ck_assert_pstr_eq(s21_strpbrk(s1, s2), strpbrk(s1, s2));
}
END_TEST

START_TEST(empty_s2) {
  char s1[] = "Some meaningless text";
  char s2[] = "";

  ck_assert_pstr_eq(s21_strpbrk(s1, s2), strpbrk(s1, s2));
}
END_TEST

START_TEST(regular_test_bpk) {
  char s1[] = "Hello World";
  char s2[] = "World";

  ck_assert_pstr_eq(s21_strpbrk(s1, s2), strpbrk(s1, s2));
}
END_TEST

START_TEST(no_match_test_bpk) {
  char s1[] = "i need this text";
  char s2[] = "sorry";

  ck_assert_pstr_eq(s21_strpbrk(s1, s2), strpbrk(s1, s2));
}
END_TEST

START_TEST(register_test_bpk) {
  char s1[] = "Hello World";
  char s2[] = "world";

  ck_assert_pstr_eq(s21_strpbrk(s1, s2), strpbrk(s1, s2));
}
END_TEST

START_TEST(one_symbol_test_bpk) {
  char s1[] = "Hi";
  char s2[] = "i";

  ck_assert_pstr_eq(s21_strpbrk(s1, s2), strpbrk(s1, s2));
}
END_TEST

//// Ildar

START_TEST(strchr_1) {
  char s1[4] = "";
  char s2 = 'n';
  ck_assert_pstr_eq(strchr(s1, s2), s21_strchr(s1, s2));
}
END_TEST

START_TEST(strchr_2) {
  char s1[5] = "Hello";
  char s2 = 'n';
  ck_assert_pstr_eq(strchr(s1, s2), s21_strchr(s1, s2));
}
END_TEST

START_TEST(strchr_3) {
  char s1[4] = "Nice";
  char s2 = 'n';
  ck_assert_pstr_eq(strchr(s1, s2), s21_strchr(s1, s2));
}
END_TEST

START_TEST(strchr_4) {
  char s1[4] = "nice";
  char s2 = 'n';
  ck_assert_pstr_eq(strchr(s1, s2), s21_strchr(s1, s2));
}
END_TEST

START_TEST(strchr_5) {
  char s1[4] = "Nice";
  char s2 = 'n';
  ck_assert_pstr_eq(strchr(s1, s2), s21_strchr(s1, s2));
}
END_TEST

///////////////////////////

START_TEST(strncmp_1) {
  char s1[100] = "Nice";
  char s2[100] = "Nice";
  int n = 0;
  int res1 = strncmp(s1, s2, n);
  int res2 = s21_strncmp(s1, s2, n);
  if (res1 > 0 && res2 > 0) {
    res1 = 1;
    res2 = 1;
  } else if (res1 < 0 && res2 < 0) {
    res1 = -1;
    res2 = -1;
  }
  ck_assert_int_eq(res1, res2);
}
END_TEST

START_TEST(strncmp_2) {
  char s1[100] = "Nice";
  char s2[100] = "";
  int n = 1;
  int res1 = strncmp(s1, s2, n);
  int res2 = s21_strncmp(s1, s2, n);
  if (res1 > 0 && res2 > 0) {
    res1 = 1;
    res2 = 1;
  } else if (res1 < 0 && res2 < 0) {
    res1 = -1;
    res2 = -1;
  }
  ck_assert_int_eq(res1, res2);
}
END_TEST

START_TEST(strncmp_3) {
  char s1[100] = "Nice";
  char s2[100] = "Nike";
  s21_size_t n = 6;
  int res1 = strncmp(s1, s2, n);
  int res2 = s21_strncmp(s1, s2, n);
  if (res1 > 0 && res2 > 0) {
    res1 = 1;
    res2 = 1;
  } else if (res1 < 0 && res2 < 0) {
    res1 = -1;
    res2 = -1;
  }
  ck_assert_int_eq(res1, res2);
}
END_TEST

START_TEST(strncmp_4) {
  char s1[100] = "Nice";
  char s2[100] = "nice";
  s21_size_t n = 4;
  int res1 = strncmp(s1, s2, n);
  int res2 = s21_strncmp(s1, s2, n);
  if (res1 > 0 && res2 > 0) {
    res1 = 1;
    res2 = 1;
  } else if (res1 < 0 && res2 < 0) {
    res1 = -1;
    res2 = -1;
  }
  ck_assert_int_eq(res1, res2);
}
END_TEST

START_TEST(strncmp_5) {
  char s1[100] = "Nice";
  char s2[100] = "nike";
  s21_size_t n = 3;
  int res1 = strncmp(s1, s2, n);
  int res2 = s21_strncmp(s1, s2, n);
  if (res1 > 0 && res2 > 0) {
    res1 = 1;
    res2 = 1;
  } else if (res1 < 0 && res2 < 0) {
    res1 = -1;
    res2 = -1;
  }
  ck_assert_int_eq(res1, res2);
}
END_TEST

///////////////////////////

START_TEST(strncpy_1) {
  char s1[4] = "Nice";
  char s2[6] = "nike";
  int n = 1;
  ck_assert_pstr_eq(strncpy(s1, s2, n), s21_strncpy(s1, s2, n));
}
END_TEST

START_TEST(strncpy_2) {
  char s1[4] = "Nice";
  char s2[3] = "ni";
  int n = 2;
  ck_assert_pstr_eq(strncpy(s1, s2, n), s21_strncpy(s1, s2, n));
}
END_TEST

START_TEST(strncpy_3) {
  char s1[4] = "Nice";
  char s2[6] = "nikerr";
  int n = 0;
  ck_assert_pstr_eq(strncpy(s1, s2, n), s21_strncpy(s1, s2, n));
}
END_TEST

START_TEST(strncpy_4) {
  char s1[4] = "Nice";
  char s2[6] = "     ";
  int n = 3;
  ck_assert_pstr_eq(strncpy(s1, s2, n), s21_strncpy(s1, s2, n));
}
END_TEST

START_TEST(strncpy_5) {
  char s1[4] = "Nice";
  char s2[6] = "";
  int n = 3;
  ck_assert_pstr_eq(strncpy(s1, s2, n), s21_strncpy(s1, s2, n));
}
END_TEST

///////////////////////////

START_TEST(strcspn_1) {
  char s1[4] = "Nice";
  char s2[4] = "iv";
  ck_assert_pstr_eq(strcspn(s1, s2) == 0 ? "equal" : "not equal",
                    s21_strcspn(s1, s2) == 0 ? "equal" : "not equal");
}
END_TEST

START_TEST(strcspn_2) {
  char s1[4] = "Nice";
  char s2[4] = "fg";
  ck_assert_pstr_eq(strcspn(s1, s2) == 0 ? "equal" : "not equal",
                    s21_strcspn(s1, s2) == 0 ? "equal" : "not equal");
}
END_TEST

START_TEST(strcspn_3) {
  char s1[4] = "Nice";
  char s2[4] = "";
  ck_assert_pstr_eq(strcspn(s1, s2) == 0 ? "equal" : "not equal",
                    s21_strcspn(s1, s2) == 0 ? "equal" : "not equal");
}
END_TEST

START_TEST(strcspn_4) {
  char s1[4] = "";
  char s2[4] = "sdf";
  ck_assert_pstr_eq(strcspn(s1, s2) == 0 ? "equal" : "not equal",
                    s21_strcspn(s1, s2) == 0 ? "equal" : "not equal");
}
END_TEST

START_TEST(strcspn_5) {
  char s1[4] = "1234";
  char s2[4] = "1234";
  ck_assert_pstr_eq(strcspn(s1, s2) == 0 ? "equal" : "not equal",
                    s21_strcspn(s1, s2) == 0 ? "equal" : "not equal");
}
END_TEST

///////////////////////////

START_TEST(strerror_1) {
  int n = 1;
  ck_assert_pstr_eq(strerror(n) == 0 ? "equal" : "not equal",
                    s21_strerror(n) == 0 ? "equal" : "not equal");
}
END_TEST

START_TEST(strerror_2) {
  s21_size_t n = 107;
  ck_assert_pstr_eq(strerror(n), s21_strerror(n));
}
END_TEST

START_TEST(strerror_3) {
  int n = 106;
  ck_assert_pstr_eq(strerror(n), s21_strerror(n));
}
END_TEST

START_TEST(strerror_4) {
  int n = 50;
  ck_assert_pstr_eq(strerror(n), s21_strerror(n));
}
END_TEST

START_TEST(strerror_5) {
  int n = 150;
  ck_assert_pstr_eq(strerror(n), s21_strerror(n));
}
END_TEST

//////////////////////////////////////////////// test of Vladimir

START_TEST(to_lower_1) {
  char *s1 = s21_to_lower("WORLD");
  char *s2 = "world";
  ck_assert_str_eq(s1, s2);
  free(s1);
}
END_TEST

START_TEST(to_lower_2) {
  char *s1 = s21_to_lower("incredible");
  char *s2 = "incredible";
  ck_assert_str_eq(s1, s2);
  free(s1);
}
END_TEST

START_TEST(to_lower_3) {
  char *s1 = s21_to_lower("LIfe");
  char *s2 = "life";
  ck_assert_str_eq(s1, s2);
  free(s1);
}
END_TEST

START_TEST(to_lower_4) {
  char *s1 = s21_to_lower("S21_scHool");
  char *s2 = "s21_school";
  ck_assert_str_eq(s1, s2);
  free(s1);
}
END_TEST

START_TEST(to_lower_5) {
  char *str1 = NULL;
  char *str2 = s21_to_lower(str1);
  ck_assert_ptr_eq(str1, str2);
  free(str2);
}
END_TEST

START_TEST(to_upper_1) {
  char *s1 = s21_to_upper("world");
  char *s2 = "WORLD";
  ck_assert_str_eq(s1, s2);
  free(s1);
}
END_TEST

START_TEST(to_upper_2) {
  char *s1 = s21_to_upper("INCREDIBLE");
  char *s2 = "INCREDIBLE";
  ck_assert_str_eq(s1, s2);
  free(s1);
}
END_TEST

START_TEST(to_upper_3) {
  char *s1 = s21_to_upper("LIfe");
  char *s2 = "LIFE";
  ck_assert_str_eq(s1, s2);
  free(s1);
}
END_TEST

START_TEST(to_upper_4) {
  char *s1 = s21_to_upper("S21_scHool");
  char *s2 = "S21_SCHOOL";
  ck_assert_str_eq(s1, s2);
  free(s1);
}
END_TEST

START_TEST(to_upper_5) {
  char str1[15] = "new\0helicopter";
  char *str2 = s21_to_upper(str1);
  ck_assert_str_eq(str2, "NEW");
  free(str2);
}
END_TEST

START_TEST(to_upper_6) {
  char *str1 = NULL;
  char *str2 = s21_to_upper(str1);
  ck_assert_ptr_eq(str1, str2);
  free(str2);
}
END_TEST

START_TEST(insert_1) {
  char *s1 = s21_insert("World", "amazing", 1);
  char *s2 = "Wamazingorld";
  ck_assert_str_eq(s1, s2);
  free(s1);
}
END_TEST

START_TEST(insert_2) {
  char *s1 = s21_insert("incredible", "WIFE", 10);
  char *s2 = "incredibleWIFE";
  ck_assert_str_eq(s1, s2);
  free(s1);
}
END_TEST

START_TEST(insert_3) {
  char str1[] = "Ma string";
  char str2[] = "";
  s21_size_t start = 5;
  char *res;
  char right[] = "Ma string";
  res = s21_insert(str1, str2, start);
  ck_assert_str_eq(right, res);
  free(res);
}
END_TEST

START_TEST(insert_4) {
  char *s1 = s21_insert("123", "amazing", 3);
  char *s2 = "123amazing";
  ck_assert_str_eq(s1, s2);
  free(s1);
}
END_TEST

START_TEST(insert_5) {
  char *s1 = s21_insert("0", "NULLis", 0);
  char *s2 = "NULLis0";
  ck_assert_str_eq(s1, s2);
  free(s1);
}
END_TEST

START_TEST(insert_6) {
  char str1[] = "";
  char str2[] = "check";
  s21_size_t start = 0;
  char *res;
  char right[] = "check";
  res = s21_insert(str1, str2, start);
  ck_assert_str_eq(res, right);
  free(res);
}
END_TEST

START_TEST(insert_7) {
  char *s1 = s21_insert("0123", NULL, 3);
  char *s2 = "0123";
  ck_assert_str_eq(s1, s2);
  free(s1);
}
END_TEST

START_TEST(insert_8) {
  char str1[1] = "";
  char str2[5] = "null";
  char *str3 = (char *)s21_insert(str1, str2, 1);
  ck_assert_ptr_eq(str3, NULL);
  free(str3);
}
END_TEST

START_TEST(s21_trim_1) {
  const char *src = "My string";
  const char *trim = "sd";
  char *res;
  res = s21_trim(src, trim);
  char right[] = "My string";
  ck_assert_str_eq(right, res);
  free(res);
}
END_TEST

START_TEST(s21_trim_2) {
  char str1[] = " sdfghjk ";
  char str2[] = " ";
  char *str3 = s21_trim(str1, str2);
  ck_assert_str_eq(str3, "sdfghjk");
  free(str3);
}
END_TEST

START_TEST(s21_trim_3) {
  char src[] = "My string";
  char trim[] = "Mg";
  void *res;
  char right[] = "y strin";
  res = s21_trim(src, trim);
  ck_assert_str_eq(res, right);
  free(res);
}
END_TEST

START_TEST(s21_trim_4) {
  char str[] = "";
  char trim_ch[] = "";
  char expected[] = "";
  char *got = s21_trim(str, trim_ch);
  ck_assert_str_eq(got, expected);
  if (got) free(got);
}
END_TEST

START_TEST(s21_trim_6) {
  char str[] = "+!009876cjhloi;ixnauQFOUXHXIW---0902R____1R2";
  char trim_ch[] = "";
  char expected[] = "+!009876cjhloi;ixnauQFOUXHXIW---0902R____1R2";
  char *got = s21_trim(str, trim_ch);
  ck_assert_str_eq(got, expected);
  if (got) free(got);
}
END_TEST

START_TEST(s21_trim_5) {
  char *str1 = "New Helicoptner";
  char *str2 = "Ner";
  char *str3 = (char *)s21_trim(str1, str2);
  ck_assert_str_eq(str3, "w Helicoptn");
  free(str3);
}
END_TEST

////////////////////////////////////////////////////////// test of Selysecr

START_TEST(simple_token_string) {
  char s21_str[] = "Maecenas++mollis_*_!malesuada massa=======vitae";
  char str[] = "Maecenas++mollis__!malesuada massa=======vitae";
  const char delim[] = "! *_=+";

  char *s21 = s21_strtok(s21_str, delim);
  char *system = strtok(str, delim);

  ck_assert_uint_eq(s21_strlen(s21), s21_strlen(system));
  ck_assert_str_eq(s21, system);

  while (s21 && system) {
    s21 = s21_strtok(NULL, delim);
    system = strtok(NULL, delim);
    ck_assert_pstr_eq(s21, system);
  }
}
END_TEST

START_TEST(hard_token_string) {
  char s21_str[] = "      Maecenas++mollis__! D !malesuada _massa=======vitae ";
  char str[] = "      Maecenas++mollis__! D !malesuada _massa=======vitae ";
  const char delim[] = "! *_=+";

  char *s21 = s21_strtok(s21_str, delim);
  char *system = strtok(str, delim);

  ck_assert_uint_eq(s21_strlen(s21), s21_strlen(system));
  ck_assert_str_eq(s21, system);

  while (s21 && system) {
    s21 = s21_strtok(NULL, delim);
    system = strtok(NULL, delim);
    ck_assert_pstr_eq(s21, system);
  }
}
END_TEST

START_TEST(not_all_delims) {
  char s21_str[] = "Maecenas++mollis__!D!malesuada_massa=======vitae";
  char str[] = "Maecenas++mollis__!D!malesuada_massa=======vitae*";
  const char delim[] = "! *_=+";

  char *s21 = s21_strtok(s21_str, delim);
  char *system = strtok(str, delim);

  ck_assert_uint_eq(s21_strlen(s21), s21_strlen(system));
  ck_assert_str_eq(s21, system);

  while (s21 && system) {
    s21 = s21_strtok(NULL, delim);
    system = strtok(NULL, delim);
    ck_assert_pstr_eq(s21, system);
  }
}
END_TEST

START_TEST(no_delims) {
  char s21_str[] = "MaecenasmollisMalesuadaMassaVitae";
  char str[] = "MaecenasmollisMalesuadaMassaVitae";
  const char delim[] = "! *_=+";

  char *s21 = s21_strtok(s21_str, delim);
  char *system = strtok(str, delim);

  ck_assert_uint_eq(s21_strlen(s21), s21_strlen(system));
  ck_assert_str_eq(s21, system);

  while (s21 && system) {
    s21 = s21_strtok(NULL, delim);
    system = strtok(NULL, delim);
    ck_assert_pstr_eq(s21, system);
  }
}
END_TEST

START_TEST(delims_str) {
  char s21_str[] = "++!!= _";
  char str[] = "++!!= _";
  const char delim[] = "! *_=+";

  char *s21 = s21_strtok(s21_str, delim);
  char *system = strtok(str, delim);

  ck_assert_pstr_eq(s21, system);
}
END_TEST

START_TEST(delims_in_word) {
  char s21_str[] = "Maece+*+nasmollis    !malesu     ada=massa___vitae";
  char str[] = "Maece++nasmollis    !malesu     ada=massa___vitae";
  const char delim[] = "! *_=+";

  char *s21 = s21_strtok(s21_str, delim);
  char *system = strtok(str, delim);

  ck_assert_uint_eq(s21_strlen(s21), s21_strlen(system));
  ck_assert_str_eq(s21, system);

  while (s21 && system) {
    s21 = s21_strtok(NULL, delim);
    system = strtok(NULL, delim);
    ck_assert_pstr_eq(s21, system);
  }
}
END_TEST

START_TEST(hard_word) {
  char s21_str[] = "!M+*+N***L M=M_F_V*H";
  char str[] = "!M+*+N***L M=M_F_V*H";
  const char delim[] = "! *_=+";

  char *s21 = s21_strtok(s21_str, delim);
  char *system = strtok(str, delim);

  ck_assert_uint_eq(s21_strlen(s21), s21_strlen(system));
  ck_assert_str_eq(s21, system);

  while (s21 && system) {
    s21 = s21_strtok(NULL, delim);
    system = strtok(NULL, delim);
    ck_assert_pstr_eq(s21, system);
  }
}
END_TEST

START_TEST(hard_string) {
  char s21_str[] =
      "        !          Maece+*+nasmol***lis    !malesu     "
      "ada=massa_f__vitae*** *** *** hi";
  char str[] =
      "        !          Maece+*+nasmol***lis    !malesu     "
      "ada=massa_f__vitae*** *** *** hi";
  const char delim[] = "! *_=+";

  char *s21 = s21_strtok(s21_str, delim);
  char *system = strtok(str, delim);

  ck_assert_uint_eq(s21_strlen(s21), s21_strlen(system));
  ck_assert_str_eq(s21, system);

  while (s21 && system) {
    s21 = s21_strtok(NULL, delim);
    system = strtok(NULL, delim);
    ck_assert_pstr_eq(s21, system);
  }
}
END_TEST

START_TEST(empty_haystack) {
  char haystack[] = "";
  char needle[] = "Hello everyone123";

  ck_assert_pstr_eq(s21_strstr(haystack, needle), strstr(haystack, needle));
}
END_TEST

START_TEST(some_needle_in_haystack) {
  char haystack[] = "hellello";
  char needle[] = "el";

  ck_assert_pstr_eq(s21_strstr(haystack, needle), strstr(haystack, needle));
}
END_TEST

START_TEST(empty_haystack_and_needle) {
  char haystack[] = "";
  char needle[] = "";

  ck_assert_pstr_eq(s21_strstr(haystack, needle), strstr(haystack, needle));
}
END_TEST

START_TEST(empty_needle) {
  char haystack[] = "Some meaningless text";
  char needle[] = "";

  ck_assert_pstr_eq(s21_strstr(haystack, needle), strstr(haystack, needle));
}
END_TEST

START_TEST(regular_test_strstr) {
  char haystack[] = "Hello World";
  char needle[] = "World";

  ck_assert_pstr_eq(s21_strstr(haystack, needle), strstr(haystack, needle));
}
END_TEST

START_TEST(no_match_test_strstr) {
  char haystack[] = "i need this text";
  char needle[] = "sorry";

  ck_assert_pstr_eq(s21_strstr(haystack, needle), strstr(haystack, needle));
}
END_TEST

START_TEST(register_test) {
  char haystack[] = "Hello World";
  char needle[] = "world";

  ck_assert_pstr_eq(s21_strstr(haystack, needle), strstr(haystack, needle));
}
END_TEST

START_TEST(one_symbol_test_strstr) {
  char haystack[] = "Hi";
  char needle[] = "i";

  ck_assert_pstr_eq(s21_strstr(haystack, needle), strstr(haystack, needle));
}
END_TEST

START_TEST(empty_str) {
  char str[] = "";
  int c = '1';

  ck_assert_pstr_eq(s21_strrchr(str, c), strrchr(str, c));
}
END_TEST

START_TEST(some_cin_str) {
  char str[] = "hellell556o";
  int c = '5';

  ck_assert_pstr_eq(s21_strrchr(str, c), strrchr(str, c));
}
END_TEST

START_TEST(empty_str_and_c) {
  char str[] = "";
  int c = '\0';

  ck_assert_pstr_eq(s21_strrchr(str, c), strrchr(str, c));
}
END_TEST

START_TEST(empty_c) {
  char str[] = "Some meaningless text";
  int c = '\0';

  ck_assert_pstr_eq(s21_strrchr(str, c), strrchr(str, c));
}
END_TEST

START_TEST(regular_test) {
  char str[] = "1Greetings";
  int c = '1';

  ck_assert_pstr_eq(s21_strrchr(str, c), strrchr(str, c));
}
END_TEST

START_TEST(no_match_test) {
  char str[] = "i need this text";
  int c = '5';

  ck_assert_pstr_eq(s21_strrchr(str, c), strrchr(str, c));
}
END_TEST

START_TEST(one_symbol_test) {
  char str[] = "1";
  int c = '1';

  ck_assert_pstr_eq(s21_strrchr(str, c), strrchr(str, c));
}
END_TEST

//////////////////////////////////////////////////////////  test of Daniil

START_TEST(memchr_1) {
  char s1[100] = "Hello, World!";
  ck_assert_pstr_eq(memchr(s1, 'W', 7), s21_memchr(s1, 'W', 7));
}
END_TEST

START_TEST(memchr_2) {
  char s1[100] = "Hello, 10 World!";
  ck_assert_pstr_eq(memchr(s1, '1', 7), s21_memchr(s1, '1', 7));
}
END_TEST

START_TEST(memchr_3) {
  char s1[100] = "s21 school!";
  ck_assert_pstr_eq(memchr(s1, '!', 11), s21_memchr(s1, '!', 11));
}
END_TEST

START_TEST(memcmp_1) {
  char s1[] = "Hello, World";
  char s2[] = "Hello, World";
  char s3[] = "Hello, World";
  int res1 = memcmp(s1, s2, 12);
  int res2 = s21_memcmp(s3, s2, 12);
  if (res1 > 0 && res2 > 0) {
    res1 = 1;
    res2 = 1;
  } else if (res1 < 0 && res2 < 0) {
    res1 = -1;
    res2 = -1;
  }
  ck_assert_int_eq(res1, res2);
}
END_TEST

START_TEST(memcmp_2) {
  char s1[15] = "Hello,Hello";
  char s2[15] = "g ";
  int res1 = memcmp(s1, s2, 11);
  int res2 = s21_memcmp(s1, s2, 11);
  if (res1 > 0 && res2 > 0) {
    res1 = 1;
    res2 = 1;
  } else if (res1 < 0 && res2 < 0) {
    res1 = -1;
    res2 = -1;
  }
  ck_assert_int_eq(res1, res2);
}
END_TEST

START_TEST(memcmp_3) {
  char s1[15] = "Hello\n\021school";
  char s2[15] = "e\0";
  int res1 = memcmp(s1, s2, 2);
  int res2 = s21_memcmp(s1, s2, 2);
  if (res1 > 0 && res2 > 0) {
    res1 = 1;
    res2 = 1;
  } else if (res1 < 0 && res2 < 0) {
    res1 = -1;
    res2 = -1;
  }
  ck_assert_int_eq(res1, res2);
}

END_TEST

START_TEST(memcpy_1) {
  char s1[100] = "AAA";
  char s3[100] = "AAA";
  char s2[100] = "!!!";
  ck_assert_pstr_eq(memcpy(s1, s2, 3), s21_memcpy(s3, s2, 3));
}
END_TEST

START_TEST(memcpy_2) {
  char s1[100] = "WorldHELLOWORLD";
  char s3[100] = "WorldHELLOWORLD";
  char s2[100] = "AAABBB";
  ck_assert_pstr_eq(memcpy(s1, s2, 8), s21_memcpy(s3, s2, 8));
}
END_TEST

START_TEST(memcpy_3) {
  char s1[100] = "Hello, 21 school!";
  char s3[100] = "Hello, 21 school!";
  char s2[100] = "1112223334";
  ck_assert_pstr_eq(memcpy(s1, s2, 10), s21_memcpy(s3, s2, 10));
}
END_TEST

START_TEST(memset_1) {
  char s1[100] = "Hello";
  ck_assert_str_eq(memset(s1, 100, 4), s21_memset(s1, 100, 4));
}
END_TEST

START_TEST(memset_2) {
  char s1[100] = "";
  ck_assert_pstr_eq(memset(s1, 87, 4), s21_memset(s1, 87, 4));
}
END_TEST

START_TEST(memset_3) {
  char s1[100] = "";
  ck_assert_pstr_eq(memset(s1, 87, 4), s21_memset(s1, 87, 4));
}
END_TEST

// sprintf

START_TEST(sprintf_c_1) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%c %2c", 'S', 'r');
  s21_sprintf(s2, "%c %2c", 'S', 'r');
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_c_2) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%8c %4c", 'S', '1');
  s21_sprintf(s2, "%8c %4c", 'S', '1');
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_c_3) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%-c %-3c", 'S', 'x');
  s21_sprintf(s2, "%-c %-3c", 'S', 'x');
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_c_4) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%ctalker", 'S');
  s21_sprintf(s2, "%ctalker", 'S');
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_c_5) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "S%calker", 't');
  s21_sprintf(s2, "S%calker", 't');
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_c_6) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "S%calker %d", 't', 2);
  s21_sprintf(s2, "S%calker %d", 't', 2);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_c_7) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%4ctalker", 'S');
  s21_sprintf(s2, "%4ctalker", 'S');
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_c_8) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%4ctal%s", 'S', "ker");
  s21_sprintf(s2, "%4ctal%s", 'S', "ker");
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_c_9) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%-4ctal%.2s", 'S', "ker");
  s21_sprintf(s2, "%-4ctal%.2s", 'S', "ker");
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_c_10) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%3c", 'f');
  s21_sprintf(s2, "%3c", 'f');
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_c_11) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%-10c%%", '1');
  s21_sprintf(s2, "%-10c%%", '1');
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_c_12) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%13c", 'M');
  s21_sprintf(s2, "%13c", 'M');
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_1) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%d\n", 563);
  s21_sprintf(s2, "%d\n", 563);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_2) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%d\n%%", 563);
  s21_sprintf(s2, "%d\n%%", 563);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_3) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%d\n", -563);
  s21_sprintf(s2, "%d\n", -563);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_4) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "max %d", INT_MAX);
  s21_sprintf(s2, "max %d", INT_MAX);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_5) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "min %d", INT_MIN);
  s21_sprintf(s2, "min %d", INT_MIN);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_6) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Stalker %d / %d / %d", 1, 2, 0);
  s21_sprintf(s2, "Stalker %d / %d / %d", 1, 2, 0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_7) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Stalker %10.2d / % d / %05d", 1, 2, 0);
  s21_sprintf(s2, "Stalker %10.2d / % d / %05d", 1, 2, 0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_8) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%4d'", 3);
  s21_sprintf(s2, "STALKER '%4d'", 3);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_9) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%3d'", -125635);
  s21_sprintf(s2, "STALKER '%3d'", -125635);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_10) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%4d'", INT_MIN);
  s21_sprintf(s2, "STALKER '%4d'", INT_MIN);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_12) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%.15d'", 2147483647);
  s21_sprintf(s2, "STALKER '%.15d'", 2147483647);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_13) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%.20d'", -2147483647 - 1);
  s21_sprintf(s2, "STALKER '%.20d'", -2147483647 - 1);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_14) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%-7d'", 56);
  s21_sprintf(s2, "STALKER '%-7d'", 56);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_15) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%-15d'", INT_MAX);
  s21_sprintf(s2, "STALKER '%-15d'", INT_MAX);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_16) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%-15d'", INT_MIN);
  s21_sprintf(s2, "STALKER '%-15d'", INT_MIN);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_17) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%5.2d'", 2023);
  s21_sprintf(s2, "STALKER '%5.2d'", 2023);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_18) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%4.2d'", INT_MAX);
  s21_sprintf(s2, "STALKER '%4.2d'", INT_MAX);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_19) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%4.2ld'", -2147483648);
  s21_sprintf(s2, "STALKER '%4.2ld'", -2147483648);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_20) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%-4.1d'", 30);
  s21_sprintf(s2, "STALKER '%-4.1d'", 30);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_21) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%-4.1d'", INT_MAX);
  s21_sprintf(s2, "STALKER '%-4.1d'", INT_MAX);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_22) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%ld'", -2147483648);
  s21_sprintf(s2, "STALKER '%ld'", -2147483648);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_23) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%+4.3d'", 325);
  s21_sprintf(s2, "STALKER '%+4.3d'", 325);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_24) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%+5.4d'", INT_MAX);
  s21_sprintf(s2, "STALKER '%+5.4d'", INT_MAX);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_25) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%+5.4d'", INT_MIN);
  s21_sprintf(s2, "STALKER '%+vd'", INT_MIN);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_26) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '% 10d'", -24);
  s21_sprintf(s2, "STALKER '% 10d'", -24);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_27) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%+4.3d'", INT_MIN);
  s21_sprintf(s2, "STALKER '%+4.3d'", INT_MIN);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_28) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%05d'", 14);
  s21_sprintf(s2, "STALKER '%05d'", 14);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_29) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%+.5d'", 543);
  s21_sprintf(s2, "STALKER '%+.5d'", 543);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_30) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '% d'", -543);
  s21_sprintf(s2, "STALKER '%+ d'", -543);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_31) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%50d'", -543);
  s21_sprintf(s2, "STALKER '%50d'", -543);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_32) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%.0d'", 0);
  s21_sprintf(s2, "STALKER '%.0d'", 0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_33) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "max %-10d", INT_MAX);
  s21_sprintf(s2, "max %-10d", INT_MAX);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_34) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "min %-10d %%", INT_MIN);
  s21_sprintf(s2, "min %-10d %%", INT_MIN);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_35) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%.0d %-5d' %%", 0, 0);
  s21_sprintf(s2, "STALKER '%.0d %-5d' %%", 0, 0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_36) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%.0d %05d'", 0, 0);
  s21_sprintf(s2, "STALKER '%.0d %05d'", 0, 0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_37) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "max %hd", SHRT_MAX);
  s21_sprintf(s2, "max %hd", SHRT_MAX);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_38) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "min %hd", SHRT_MIN);
  s21_sprintf(s2, "min %hd", SHRT_MIN);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_39) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%4hd'", (short int)9);
  s21_sprintf(s2, "STALKER '%4hd'", (short int)9);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_40) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%9hd'", SHRT_MAX);
  s21_sprintf(s2, "STALKER '%9hd'", SHRT_MAX);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_41) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%9hd'", SHRT_MIN);
  s21_sprintf(s2, "STALKER '%9hd'", SHRT_MIN);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_42) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%.1hd'", (short int)11);
  s21_sprintf(s2, "STALKER '%.1hd'", (short int)11);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_43) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%.1hd'", SHRT_MAX);
  s21_sprintf(s2, "STALKER '%.1hd'", SHRT_MAX);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_44) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%.1hd'", SHRT_MIN);
  s21_sprintf(s2, "STALKER '%.1hd'", SHRT_MIN);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_45) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%07hd'", (short int)11);
  s21_sprintf(s2, "STALKER '%07hd'", (short int)11);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_46) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%07hd'", SHRT_MAX);
  s21_sprintf(s2, "STALKER '%07hd'", SHRT_MAX);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_47) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%07hd'", SHRT_MIN);
  s21_sprintf(s2, "STALKER '%07hd'", SHRT_MIN);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_48) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "max %ld", LONG_MAX);
  s21_sprintf(s2, "max %ld", LONG_MAX);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_49) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "min %ld", LONG_MIN);
  s21_sprintf(s2, "min %ld", LONG_MIN);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_50) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%4ld'", 92299993333);
  s21_sprintf(s2, "STALKER '%4ld'", 92299993333);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_51) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%9ld'", LONG_MAX);
  s21_sprintf(s2, "STALKER '%9ld'", LONG_MAX);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_52) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%9ld'", LONG_MIN);
  s21_sprintf(s2, "STALKER '%9ld'", LONG_MIN);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_53) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%.1ld'", 1122222223652);
  s21_sprintf(s2, "STALKER '%.1ld'", 1122222223652);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_54) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%.1ld'", LONG_MAX);
  s21_sprintf(s2, "STALKER '%.1ld'", LONG_MAX);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_55) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%.1ld'", LONG_MIN);
  s21_sprintf(s2, "STALKER '%.1ld'", LONG_MIN);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_56) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%07ld'", 1122222223652);
  s21_sprintf(s2, "STALKER '%07ld'", 1122222223652);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_d_57) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%07ld'", LONG_MAX);
  s21_sprintf(s2, "STALKER '%07ld'", LONG_MAX);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_s_1) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%s", "S.t.a.l.k.e.r.");
  s21_sprintf(s2, "%s", "S.t.a.l.k.e.r.");
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_s_2) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%.1s", "S.t.a.l.k.e.r.");
  s21_sprintf(s2, "%.1s", "S.t.a.l.k.e.r.");
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_s_3) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%-10s", "S.t.a.l.k.e.r.");
  s21_sprintf(s2, "%-10s", "S.t.a.l.k.e.r.");
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_s_4) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%.1s %s", "S.t.a.l.k.e.r.", "Clear sky");
  s21_sprintf(s2, "%.1s %s", "S.t.a.l.k.e.r.", "Clear sky");
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_s_5) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%.1s %s", "S.t.a.l.k.e.r.", "Clear sky");
  s21_sprintf(s2, "%.1s %s", "S.t.a.l.k.e.r.", "Clear sky");
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_s_6) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%s", "");
  s21_sprintf(s2, "%s", "");
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_s_7) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%s", " ");
  s21_sprintf(s2, "%s", " ");
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_s_8) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%-10s", "Hello");
  s21_sprintf(s2, "%-10s", "Hello");
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_s_9) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%s", "Hello World");
  s21_sprintf(s2, "%s", "Hello World");
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_s_10) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%s %s %.3s", "S.t.a.l.k.e.r.", "Clear sky", "Shad\0w");
  s21_sprintf(s2, "%s %s %.3s", "S.t.a.l.k.e.r.", "Clear sky", "Shad\0w");
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_s_11) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%s", "Shad\0w");
  s21_sprintf(s2, "%s", "Shad\0w");
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_s_12) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%s", "Shad\0w\ntest");
  s21_sprintf(s2, "%s", "Shad\0w\ntest");
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_s_13) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%10s", "Shad\0w\0test");
  s21_sprintf(s2, "%10s", "Shad\0w\0test");
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_s_14) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%4s %19s", "Hello", "S.t.a.l.k.e.r.");
  s21_sprintf(s2, "%4s %19s", "Hello", "S.t.a.l.k.e.r.");
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_s_15) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%10.0s", "Drop");
  s21_sprintf(s2, "%10.0s", "Drop");
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_s_16) {
  char s1[1280] = "";
  char s2[1280] = "";
  sprintf(s1, "%210s", "Tears");
  s21_sprintf(s2, "%210s", "Tears");
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_s_17) {
  char s1[1280] = "";
  char s2[1280] = "";
  sprintf(s1, "%210s", "Tears\ndont\nfall");
  s21_sprintf(s2, "%210s", "Tears\ndont\nfall");
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_s_18) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%-5.5s", "Master");
  s21_sprintf(s2, "%-5.5s", "Master");
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_s_19) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%5.5s", "Master");
  s21_sprintf(s2, "%5.5s", "Master");
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_s_20) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%4.4s", "Master");
  s21_sprintf(s2, "%4.4s", "Master");
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_1) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%f", 256.128);
  s21_sprintf(s2, "%f", 256.128);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_2) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%0f", 256.128);
  s21_sprintf(s2, "%0f", 256.128);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_3) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%-10f", 256.128);
  s21_sprintf(s2, "%-10f", 256.128);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_4) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%f", 0.965233);
  s21_sprintf(s2, "%f", 0.965233);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_5) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%0.2f", 0.965233);
  s21_sprintf(s2, "%0.2f", 0.965233);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_6) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%+8.6f", 0.965233);
  s21_sprintf(s2, "%+8.6f", 0.965233);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_7) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%+8.6f", -0.9652);
  s21_sprintf(s2, "%+8.6f", -0.9652);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_8) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%8.3f", -0.9652);
  s21_sprintf(s2, "%8.3f", -0.9652);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_9) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%.0lf", -0.9652);
  s21_sprintf(s2, "%.0f", -0.9652);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_10) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%10.0f", 333.333);
  s21_sprintf(s2, "%10.0f", 333.333);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_11) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%-10.0f", 333.333);
  s21_sprintf(s2, "%-10.0f", 333.333);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_12) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%-1.0f", 333.333);
  s21_sprintf(s2, "%-1.0f", 333.333);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_13) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%1.0f", 333.333);
  s21_sprintf(s2, "%1.0f", 333.333);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_14) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%+1.9f", -333.999);
  s21_sprintf(s2, "%+1.9f", -333.999);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_15) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "% 15f", -333.999);
  s21_sprintf(s2, "% 15f", -333.999);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_16) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%-1.0f", 1.11);
  s21_sprintf(s2, "%-1.0f", 1.11);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_17) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%1.0f", 0.112);
  s21_sprintf(s2, "%1.0f", 0.112);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_18) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%+1.9f", -0.112);
  s21_sprintf(s2, "%+1.9f", -0.112);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_19) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%-1.0f", 1.0);
  s21_sprintf(s2, "%-1.0f", 1.0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_20) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%1.0f", 1.0);
  s21_sprintf(s2, "%1.0f", 1.0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_21) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%+1.9f", -1.0);
  s21_sprintf(s2, "%+1.9f", -1.0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_22) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%015f", 555.);
  s21_sprintf(s2, "%015f", 555.);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_23) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%05.0f", 555.5);
  s21_sprintf(s2, "%05.0f", 555.5);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_24) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%+08.06f", 125.7777);
  s21_sprintf(s2, "%+08.06f", 125.7777);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_25) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%08.3f", 125.7);
  s21_sprintf(s2, "%08.3f", 125.7);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_26) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%08.3f", 5.);
  s21_sprintf(s2, "%08.3f", 5.);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_27) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%+8.3f", (double)4);
  s21_sprintf(s2, "%+8.3f", (double)4);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_28) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%+8f", (double)4);
  s21_sprintf(s2, "%+8f", (double)4);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_29) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "% f", (double)4);
  s21_sprintf(s2, "% f", (double)4);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_30) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%+f", (double)4);
  s21_sprintf(s2, "%+f", (double)4);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_31) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "% -12f", 20.8);
  s21_sprintf(s2, "% -12f", 20.8);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_32) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%+10f", (double)4);
  s21_sprintf(s2, "%+10f", (double)4);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_33) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "% -12.5f", 20.8);
  s21_sprintf(s2, "% -12.5f", 20.8);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_34) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "% 10f", 20.8);
  s21_sprintf(s2, "% 10f", 20.8);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_35) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%+-10f", -20.8);
  s21_sprintf(s2, "%+-10f", -20.8);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_36) {
  char s1[1024] = "";
  char s2[1024] = "";
  sprintf(s1, "%lf", 9.7253);
  s21_sprintf(s2, "%lf", 9.7253);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_37) {
  char s1[1024] = "";
  char s2[1024] = "";
  sprintf(s1, "%.14f", 9.7253);
  s21_sprintf(s2, "%.14f", 9.7253);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_38) {
  char s1[1024] = "";
  char s2[1024] = "";
  sprintf(s1, "%.19f", 1.0);
  s21_sprintf(s2, "%.19f", 1.0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_39) {
  char s1[1024] = "";
  char s2[1024] = "";
  sprintf(s1, "%.12f", -9.7253);
  s21_sprintf(s2, "%.12f", -9.7253);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_40) {
  char s1[1024] = "";
  char s2[1024] = "";
  sprintf(s1, "%.4f", 19.99999);
  s21_sprintf(s2, "%.4f", 19.99999);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_41) {
  char s1[1024] = "";
  char s2[1024] = "";
  sprintf(s1, "% 5f", 0.00000012);
  s21_sprintf(s2, "% 5f", 0.00000012);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_42) {
  char s1[1024] = "";
  char s2[1024] = "";
  sprintf(s1, "% 3f", (double)0);
  s21_sprintf(s2, "% 3f", (double)0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_43) {
  char s1[1024] = "";
  char s2[1024] = "";
  sprintf(s1, "%-+10f", 4.4);
  s21_sprintf(s2, "%-+10f", 4.4);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_44) {
  char s1[1024] = "";
  char s2[1024] = "";
  sprintf(s1, "%.3f", -4.99999);
  s21_sprintf(s2, "%.3f", -4.99999);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_45) {
  char s1[1024] = "";
  char s2[1024] = "";
  sprintf(s1, "%#.0f", -4.99999);
  s21_sprintf(s2, "%#.0f", -4.99999);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_46) {
  char s1[1024] = "";
  char s2[1024] = "";
  sprintf(s1, "%03.f", (double)0);
  s21_sprintf(s2, "%03.f", (double)0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_47) {
  char s1[1024] = "";
  char s2[1024] = "";
  sprintf(s1, "%-10f", (double)0);
  s21_sprintf(s2, "%-10f", (double)0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_48) {
  char s1[1024] = "";
  char s2[1024] = "";
  sprintf(s1, "%#.0f", (double)0);
  s21_sprintf(s2, "%#.0f", (double)0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_49) {
  char s1[1024] = "";
  char s2[1024] = "";
  sprintf(s1, "%5.4f", (double)0);
  s21_sprintf(s2, "%5.4f", (double)0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_f_50) {
  char s1[1024] = "";
  char s2[1024] = "";
  sprintf(s1, "%4.5f", (double)0);
  s21_sprintf(s2, "%4.5f", (double)0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_p_1) {
  char str1[1024];
  char str2[1024];
  char ptr[10];
  s21_sprintf(str1, "%p", ptr);
  sprintf(str2, "%p", ptr);
  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(sprintf_p_2) {
  char str1[1024];
  char str2[1024];
  char ptr[10];
  s21_sprintf(str1, "%15p", ptr);
  sprintf(str2, "%15p", ptr);
  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(sprintf_p_3) {
  char str1[1024];
  char str2[1024];
  char ptr[10];
  s21_sprintf(str1, "%5p", ptr);
  sprintf(str2, "%5p", ptr);
  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(sprintf_p_4) {
  char str1[1024];
  char str2[1024];
  char ptr[10];
  s21_sprintf(str1, "%-20p", ptr);
  sprintf(str2, "%-20p", ptr);
  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(sprintf_p_5) {
  char str1[1024];
  char str2[1024];
  char ptr[10];
  s21_sprintf(str1, "%18p", ptr);
  sprintf(str2, "%18p", ptr);
  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(sprintf_p_6) {
  char str1[1024];
  char str2[1024];
  char ptr[10];
  s21_sprintf(str1, "%9p", ptr);
  sprintf(str2, "%9p", ptr);
  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(sprintf_p_7) {
  char str1[1024];
  char str2[1024];
  char ptr[10];
  s21_sprintf(str1, "%20p", ptr);
  sprintf(str2, "%20p", ptr);
  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(sprintf_p_8) {
  char str1[1024];
  char str2[1024];
  char ptr[10];
  s21_sprintf(str1, "%5p", ptr);
  sprintf(str2, "%5p", ptr);
  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(sprintf_u_1) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%2.5u%%\n", (unsigned int)15);
  s21_sprintf(s2, "%2.5u%%\n", (unsigned int)15);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_2) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%-10u%%\n", (unsigned int)232);
  s21_sprintf(s2, "%-10u%%\n", (unsigned int)232);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_3) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%-10hu%%\n", (short unsigned int)232);
  s21_sprintf(s2, "%-10hu%%\n", (short unsigned int)232);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_4) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%.5u%%\n", (unsigned int)8);
  s21_sprintf(s2, "%.5u%%\n", (unsigned int)8);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_5) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%-10u%%\n", (unsigned int)232);
  s21_sprintf(s2, "%-10u%%\n", (unsigned int)232);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_6) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "max %u", UINT_MAX);
  s21_sprintf(s2, "max %u", UINT_MAX);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_7) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "min %u", (unsigned int)0);
  s21_sprintf(s2, "min %u", (unsigned int)0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_8) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER %u / %u / %u / %u", (unsigned int)9, (unsigned int)8,
          (unsigned int)2, (unsigned int)0);
  s21_sprintf(s2, "STALKER %u / %u / %u / %u", (unsigned int)9, (unsigned int)8,
              (unsigned int)2, (unsigned int)0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_9) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER %u / %u / %u / %s", (unsigned int)9, (unsigned int)0,
          (unsigned int)2, "LOL");
  s21_sprintf(s2, "STALKER %u / %u / %u / %s", (unsigned int)9, (unsigned int)0,
              (unsigned int)2, "LOL");
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_10) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%4u'", (unsigned int)9);
  s21_sprintf(s2, "STALKER '%4u'", (unsigned int)9);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_11) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%4u'", UINT_MAX);
  s21_sprintf(s2, "STALKER '%4u'", UINT_MAX);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_12) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%4u'", (unsigned int)0);
  s21_sprintf(s2, "STALKER '%4u'", (unsigned int)0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_13) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%.1u'", (unsigned int)11);
  s21_sprintf(s2, "STALKER '%.1u'", (unsigned int)11);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_14) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%.1u'", UINT_MAX);
  s21_sprintf(s2, "STALKER '%.1u'", UINT_MAX);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_15) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%.1u'", (unsigned int)0);
  s21_sprintf(s2, "STALKER '%.1u'", (unsigned int)0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_16) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%07u'", (unsigned int)11123);
  s21_sprintf(s2, "STALKER '%07u'", (unsigned int)11123);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_17) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%07u'", UINT_MAX);
  s21_sprintf(s2, "STALKER '%07u'", UINT_MAX);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_18) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%07u'", (unsigned int)0);
  s21_sprintf(s2, "STALKER '%07u'", (unsigned int)0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_19) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%-7u'", (unsigned int)11123);
  s21_sprintf(s2, "STALKER '%-7u'", (unsigned int)11123);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_20) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%-7u'", UINT_MAX);
  s21_sprintf(s2, "STALKER '%-7u'", UINT_MAX);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_21) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%-7u'", (unsigned int)0);
  s21_sprintf(s2, "STALKER '%-7u'", (unsigned int)0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_22) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%15.5u'", (unsigned int)321);
  s21_sprintf(s2, "STALKER '%15.5u'", (unsigned int)321);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_23) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%15.5u'", UINT_MAX);
  s21_sprintf(s2, "STALKER '%15.5u'", UINT_MAX);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_24) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%15.5u'", (unsigned int)0);
  s21_sprintf(s2, "STALKER '%15.5u'", (unsigned int)0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_25) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%-20.1u'", (unsigned int)128);
  s21_sprintf(s2, "STALKER '%-20.1u'", (unsigned int)128);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_26) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%-20.1u'", UINT_MAX);
  s21_sprintf(s2, "STALKER '%-20.1u'", UINT_MAX);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_27) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%-20.1u'", (unsigned int)0);
  s21_sprintf(s2, "STALKER '%-20.1u'", (unsigned int)0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_28) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%-20u'", (unsigned int)0);
  s21_sprintf(s2, "STALKER '%-20u'", (unsigned int)0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_29) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%-5u'", (unsigned int)235);
  s21_sprintf(s2, "STALKER '%-5u'", (unsigned int)235);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_30) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%010u'", (unsigned int)0);
  s21_sprintf(s2, "STALKER '%010u'", (unsigned int)0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_31) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%-10hu%%\n", (short unsigned int)500);
  s21_sprintf(s2, "%-10hu%%\n", (short unsigned int)500);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_32) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%.5hu%%\n", (short unsigned int)4);
  s21_sprintf(s2, "%.5hu%%\n", (short unsigned int)4);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_33) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%-10hu%%\n", (short unsigned int)421);
  s21_sprintf(s2, "%-10hu%%\n", (short unsigned int)421);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_34) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "max %hu", USHRT_MAX);
  s21_sprintf(s2, "max %hu", USHRT_MAX);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_35) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "min %hu", (short unsigned int)0);
  s21_sprintf(s2, "min %hu", (short unsigned int)0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_36) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%4hu'", (short unsigned int)9);
  s21_sprintf(s2, "STALKER '%4hu'", (short unsigned int)9);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_37) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%4hu'", USHRT_MAX);
  s21_sprintf(s2, "STALKER '%4hu'", USHRT_MAX);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_38) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%4hu'", (short unsigned int)0);
  s21_sprintf(s2, "STALKER '%4hu'", (short unsigned int)0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_39) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%.1hu'", (short unsigned int)11);
  s21_sprintf(s2, "STALKER '%.1hu'", (short unsigned int)11);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_40) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%.1hu'", USHRT_MAX);
  s21_sprintf(s2, "STALKER '%.1hu'", USHRT_MAX);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_41) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%.1hu'", (short unsigned int)0);
  s21_sprintf(s2, "STALKER '%.1hu'", (short unsigned int)0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_42) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%07hu'", (short unsigned int)11);
  s21_sprintf(s2, "STALKER '%07hu'", (short unsigned int)11);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_43) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%07hu'", USHRT_MAX);
  s21_sprintf(s2, "STALKER '%07hu'", USHRT_MAX);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_44) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%07hu'", (short unsigned int)0);
  s21_sprintf(s2, "STALKER '%07hu'", (short unsigned int)0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_45) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "STALKER '%-7hu'", (short unsigned int)11);
  s21_sprintf(s2, "STALKER '%-7hu'", (short unsigned int)11);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_46) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%.5lu%%\n", (long unsigned int)43445623111);
  s21_sprintf(s2, "%.5lu%%\n", (long unsigned int)43445623111);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_47) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%-10lu%%\n", (long unsigned int)4211231245467546);
  s21_sprintf(s2, "%-10lu%%\n", (long unsigned int)4211231245467546);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_48) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "max %lu", ULONG_MAX);
  s21_sprintf(s2, "max %lu", ULONG_MAX);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_49) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%4lu'", (long unsigned int)92342214334);
  s21_sprintf(s2, "Clear sky '%4lu'", (long unsigned int)92342214334);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_50) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%4lu'", ULONG_MAX);
  s21_sprintf(s2, "Clear sky '%4lu'", ULONG_MAX);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_51) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%.21lu'", (long unsigned int)123423463451);
  s21_sprintf(s2, "Clear sky '%.21lu'", (long unsigned int)123423463451);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_52) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%.21lu'", ULONG_MAX);
  s21_sprintf(s2, "Clear sky '%.21lu'", ULONG_MAX);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_53) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%022lu'", (long unsigned int)123234545311);
  s21_sprintf(s2, "Clear sky '%022lu'", (long unsigned int)123234545311);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_u_54) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%022lu'", ULONG_MAX);
  s21_sprintf(s2, "Clear sky '%022lu'", ULONG_MAX);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_o_1) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%o'", 1236);
  s21_sprintf(s2, "Clear sky '%o'", 1236);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_o_2) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%o'", 1236);
  s21_sprintf(s2, "Clear sky '%o'", 1236);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_o_3) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%o'", 1236);
  s21_sprintf(s2, "Clear sky '%o'", 1236);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_o_4) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%o'", 1236);
  s21_sprintf(s2, "Clear sky '%o'", 1236);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_o_5) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%o'", 0);
  s21_sprintf(s2, "Clear sky '%o'", 0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_o_6) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%10o'", 1236);
  s21_sprintf(s2, "Clear sky '%10o'", 1236);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_o_7) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%-10o'", 01230);
  s21_sprintf(s2, "Clear sky '%-10o'", 01230);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_o_8) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%#o'", 1236);
  s21_sprintf(s2, "Clear sky '%#o'", 1236);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_o_9) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%lo'", (unsigned long int)1236);
  s21_sprintf(s2, "Clear sky '%lo'", (unsigned long int)1236);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_o_10) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky %o, %o, %ho, %.5o, %5.o", 1236, (unsigned)14,
          (unsigned short)1441, (unsigned)14414, (unsigned)9681);
  s21_sprintf(s2, "Clear sky %o, %o, %ho, %.5o, %5.o", 1236, (unsigned)14,
              (unsigned short)1441, (unsigned)14414, (unsigned)9681);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_o_11) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%010lo'", (unsigned long int)1236);
  s21_sprintf(s2, "Clear sky '%010lo'", (unsigned long int)1236);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_o_12) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%5.5o'", 01236);
  s21_sprintf(s2, "Clear sky '%5.5o'", 01236);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_o_13) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%5o'", 0x965547);
  s21_sprintf(s2, "Clear sky '%5o'", 0x965547);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_o_14) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%010o'", 1236);
  s21_sprintf(s2, "Clear sky '%010o'", 1236);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_o_15) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%010o'", 1236);
  s21_sprintf(s2, "Clear sky '%010o'", 1236);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_o_16) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%o'", 0);
  s21_sprintf(s2, "Clear sky '%o'", 0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_o_17) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%05o'", 0);
  s21_sprintf(s2, "Clear sky '%05o'", 0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_o_18) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%o'", 0x12320);
  s21_sprintf(s2, "Clear sky '%o'", 0x12320);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_o_19) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%o'", -1236);
  s21_sprintf(s2, "Clear sky '%o'", -1236);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_o_20) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%#010o'", 1236);
  s21_sprintf(s2, "Clear sky '%#010o'", 1236);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_x_1) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%#010x'", 1236);
  s21_sprintf(s2, "Clear sky '%#010x'", 1236);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_x_2) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%x'", (unsigned)INT32_MIN);
  s21_sprintf(s2, "Clear sky '%x'", (unsigned)INT32_MIN);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_x_3) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%x'", (unsigned)INT32_MAX);
  s21_sprintf(s2, "Clear sky '%x'", (unsigned)INT32_MAX);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_x_4) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%X'", (unsigned)INT32_MIN);
  s21_sprintf(s2, "Clear sky '%X'", (unsigned)INT32_MIN);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_x_5) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%X'", (unsigned)INT32_MAX);
  s21_sprintf(s2, "Clear sky '%X'", (unsigned)INT32_MAX);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_x_6) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky %x%x%x%x%x", 0x325, 135, 0, -1230, -123213123);
  s21_sprintf(s2, "Clear sky %x%x%x%x%x", 0x325, 135, 0, -1230, -123213123);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_x_7) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky %X%X%X%X%X", 0x325, 135, 0, -1230, -123213123);
  s21_sprintf(s2, "Clear sky %X%X%X%X%X", 0x325, 135, 0, -1230, -123213123);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_x_8) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%-3x'", (unsigned)INT32_MIN);
  s21_sprintf(s2, "Clear sky '%-3x'", (unsigned)INT32_MIN);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_x_9) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%09x'", 01236);
  s21_sprintf(s2, "Clear sky '%09x'", 01236);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_x_10) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%-9x'", 01236);
  s21_sprintf(s2, "Clear sky '%-9x'", 01236);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_x_11) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%x'", 0Xd);
  s21_sprintf(s2, "Clear sky '%x'", 0Xd);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_x_12) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%X'", 0Xd);
  s21_sprintf(s2, "Clear sky '%X'", 0Xd);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_x_13) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%#X'", 0Xd);
  s21_sprintf(s2, "Clear sky '%#X'", 0Xd);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_x_14) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%.8x'", 1236);
  s21_sprintf(s2, "Clear sky '%.8x'", 1236);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_x_15) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%#010x'", 0);
  s21_sprintf(s2, "Clear sky '%#010x'", 0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_x_16) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%010x'", 0);
  s21_sprintf(s2, "Clear sky '%010x'", 0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_x_17) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%10x'", 0);
  s21_sprintf(s2, "Clear sky '%10x'", 0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_x_18) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%x'", 0);
  s21_sprintf(s2, "Clear sky '%x'", 0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_x_19) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%-9x'", 13465498);
  s21_sprintf(s2, "Clear sky '%-9x'", 13465498);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_x_20) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "Clear sky '%-7x'", 1236);
  s21_sprintf(s2, "Clear sky '%-7x'", 1236);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_e_1) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%e", 256.128);
  s21_sprintf(s2, "%e", 256.128);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_e_2) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%0E", 256.128);
  s21_sprintf(s2, "%0E", 256.128);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_e_3) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%.0e", 256.128);
  s21_sprintf(s2, "%.0e", 256.128);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_e_4) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%.0Le", (long double)0.9152336546846565);
  s21_sprintf(s2, "%.0Le", (long double)0.9152336546846565);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_e_5) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%.0LE", (long double)0.9152336546846565);
  s21_sprintf(s2, "%.0LE", (long double)0.9152336546846565);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_e_6) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%.10LE", (long double)0.9152336546846565);
  s21_sprintf(s2, "%.10LE", (long double)0.9152336546846565);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_e_7) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%.11E", -0.96523365468465);
  s21_sprintf(s2, "%.11E", -0.96523365468465);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_e_8) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%8.3e", -0.9652);
  s21_sprintf(s2, "%8.3e", -0.9652);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_e_9) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%e", 72537572375.1431341);
  s21_sprintf(s2, "%e", 72537572375.1431341);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_e_10) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%015LE", (long double)-7.1431341);
  s21_sprintf(s2, "%015LE", (long double)-7.1431341);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_e_11) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%015.2e", -7.1431341);
  s21_sprintf(s2, "%015.2e", -7.1431341);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_e_12) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%010.2e", 7.1431341);
  s21_sprintf(s2, "%010.2e", 7.1431341);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_e_13) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%1.0e", 0.00000698);
  s21_sprintf(s2, "%1.0e", 0.00000698);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_e_14) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%e", 0.00000698);
  s21_sprintf(s2, "%e", 0.00000698);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_e_15) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%010e", 0.00000698);
  s21_sprintf(s2, "%010e", 0.00000698);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_e_16) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%+1.9e", 0.00000698);
  s21_sprintf(s2, "%+1.9e", 0.00000698);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_e_17) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%+15.9e", 0.9999999);
  s21_sprintf(s2, "%+15.9e", 0.9999999);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_e_18) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%+1.9E", -0.112);
  s21_sprintf(s2, "%+1.9E", -0.112);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_e_19) {
  char s1[128] = "";
  char s2[128] = "";
  float val = 0;
  double val1 = 0;
  long double val2 = 3515315.153151;
  float val3 = 5.5;
  double val4 = 0.094913941;
  long double val5 = 95919539159.53151351131;
  sprintf(s1, "% .0e %.le %Le %e %le %Le", val, val1, val2, val3, val4, val5);
  s21_sprintf(s2, "% .0e %.le %Le %e %le %Le", val, val1, val2, val3, val4,
              val5);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_e_20) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%1.0e", NAN);
  s21_sprintf(s2, "%1.0e", NAN);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_e_21) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%e", 0.00569);
  s21_sprintf(s2, "%e", 0.00569);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_e_22) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%-10e", 0.00569);
  s21_sprintf(s2, "%-10e", 0.00569);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_e_23) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%-10e", NAN);
  s21_sprintf(s2, "%-10e", NAN);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_e_24) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%+08.06e", 125.7777);
  s21_sprintf(s2, "%+08.06e", 125.7777);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_e_25) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%08.3e", 125.7);
  s21_sprintf(s2, "%08.3e", 125.7);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_e_26) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%08.3e", 5.);
  s21_sprintf(s2, "%08.3e", 5.);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_e_27) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%+8.3e", (double)0);
  s21_sprintf(s2, "%+8.3e", (double)0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_e_28) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%+8E", (double)0);
  s21_sprintf(s2, "%+8E", (double)0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_e_29) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "% e", (double)0);
  s21_sprintf(s2, "% e", (double)0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_e_30) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%+E", (double)0);
  s21_sprintf(s2, "%+E", (double)0);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_g) {
  char s1[128] = "";
  char s2[128] = "";
  sprintf(s1, "%g", NAN);
  s21_sprintf(s2, "%g", NAN);
  ck_assert_str_eq(s1, s2);
}
END_TEST

START_TEST(sprintf_empty) {
  char str1[128];
  char str2[128];
  ck_assert_int_eq(s21_sprintf(str1, "abc"), sprintf(str2, "abc"));

  ck_assert_str_eq(str1, str2);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  /// strpbrk
  tcase_add_test(tc1_1, empty_s1);
  tcase_add_test(tc1_1, some_s1_in_s2);
  tcase_add_test(tc1_1, empty_s1s2);
  tcase_add_test(tc1_1, empty_s2);
  tcase_add_test(tc1_1, regular_test_bpk);
  tcase_add_test(tc1_1, no_match_test_bpk);
  tcase_add_test(tc1_1, register_test_bpk);
  tcase_add_test(tc1_1, one_symbol_test_bpk);
  // Ildar
  tcase_add_test(tc1_1, strchr_1);
  tcase_add_test(tc1_1, strchr_2);
  tcase_add_test(tc1_1, strchr_3);
  tcase_add_test(tc1_1, strchr_4);
  tcase_add_test(tc1_1, strchr_5);
  tcase_add_test(tc1_1, strncmp_1);
  tcase_add_test(tc1_1, strncmp_2);
  tcase_add_test(tc1_1, strncmp_3);
  tcase_add_test(tc1_1, strncmp_4);
  tcase_add_test(tc1_1, strncmp_5);
  tcase_add_test(tc1_1, strncpy_1);
  tcase_add_test(tc1_1, strncpy_2);
  tcase_add_test(tc1_1, strncpy_3);
  tcase_add_test(tc1_1, strncpy_4);
  tcase_add_test(tc1_1, strncpy_5);
  tcase_add_test(tc1_1, strcspn_1);
  tcase_add_test(tc1_1, strcspn_2);
  tcase_add_test(tc1_1, strcspn_3);
  tcase_add_test(tc1_1, strcspn_4);
  tcase_add_test(tc1_1, strcspn_5);
  tcase_add_test(tc1_1, strerror_1);
  tcase_add_test(tc1_1, strerror_2);
  tcase_add_test(tc1_1, strerror_3);
  tcase_add_test(tc1_1, strerror_4);
  tcase_add_test(tc1_1, strerror_5);
  // test of Vladimir
  tcase_add_test(tc1_1, to_lower_1);
  tcase_add_test(tc1_1, to_lower_2);
  tcase_add_test(tc1_1, to_lower_3);
  tcase_add_test(tc1_1, to_lower_4);
  tcase_add_test(tc1_1, to_lower_5);
  tcase_add_test(tc1_1, to_upper_1);
  tcase_add_test(tc1_1, to_upper_2);
  tcase_add_test(tc1_1, to_upper_3);
  tcase_add_test(tc1_1, to_upper_4);
  tcase_add_test(tc1_1, to_upper_5);
  tcase_add_test(tc1_1, to_upper_6);
  tcase_add_test(tc1_1, insert_1);
  tcase_add_test(tc1_1, insert_2);
  tcase_add_test(tc1_1, insert_3);
  tcase_add_test(tc1_1, insert_4);
  tcase_add_test(tc1_1, insert_5);
  tcase_add_test(tc1_1, insert_6);
  tcase_add_test(tc1_1, insert_7);
  tcase_add_test(tc1_1, insert_8);
  tcase_add_test(tc1_1, s21_trim_1);
  tcase_add_test(tc1_1, s21_trim_2);
  tcase_add_test(tc1_1, s21_trim_3);
  tcase_add_test(tc1_1, s21_trim_4);
  tcase_add_test(tc1_1, s21_trim_6);
  tcase_add_test(tc1_1, s21_trim_5);
  // Test of Selysecr
  tcase_add_test(tc1_1, simple_token_string);
  tcase_add_test(tc1_1, hard_token_string);
  tcase_add_test(tc1_1, not_all_delims);
  tcase_add_test(tc1_1, no_delims);
  tcase_add_test(tc1_1, delims_str);
  tcase_add_test(tc1_1, delims_in_word);
  tcase_add_test(tc1_1, hard_word);
  tcase_add_test(tc1_1, hard_string);
  tcase_add_test(tc1_1, empty_haystack);
  tcase_add_test(tc1_1, some_needle_in_haystack);
  tcase_add_test(tc1_1, empty_haystack_and_needle);
  tcase_add_test(tc1_1, empty_needle);
  tcase_add_test(tc1_1, regular_test_strstr);
  tcase_add_test(tc1_1, no_match_test_strstr);
  tcase_add_test(tc1_1, register_test);
  tcase_add_test(tc1_1, one_symbol_test_strstr);
  tcase_add_test(tc1_1, empty_str);
  tcase_add_test(tc1_1, some_cin_str);
  tcase_add_test(tc1_1, empty_c);
  tcase_add_test(tc1_1, empty_str_and_c);
  tcase_add_test(tc1_1, regular_test);
  tcase_add_test(tc1_1, no_match_test);
  tcase_add_test(tc1_1, one_symbol_test);
  // test of Daniil
  tcase_add_test(tc1_1, memchr_1);
  tcase_add_test(tc1_1, memchr_2);
  tcase_add_test(tc1_1, memchr_3);
  tcase_add_test(tc1_1, memcmp_1);
  tcase_add_test(tc1_1, memcmp_2);
  tcase_add_test(tc1_1, memcmp_3);
  tcase_add_test(tc1_1, memcpy_1);
  tcase_add_test(tc1_1, memcpy_2);
  tcase_add_test(tc1_1, memcpy_3);
  tcase_add_test(tc1_1, memset_1);
  tcase_add_test(tc1_1, memset_2);
  tcase_add_test(tc1_1, memset_3);
  // sprintf
  tcase_add_test(tc1_1, sprintf_c_1);
  tcase_add_test(tc1_1, sprintf_c_2);
  tcase_add_test(tc1_1, sprintf_c_3);
  tcase_add_test(tc1_1, sprintf_c_4);
  tcase_add_test(tc1_1, sprintf_c_5);
  tcase_add_test(tc1_1, sprintf_c_6);
  tcase_add_test(tc1_1, sprintf_c_7);
  tcase_add_test(tc1_1, sprintf_c_8);
  tcase_add_test(tc1_1, sprintf_c_9);
  tcase_add_test(tc1_1, sprintf_c_10);
  tcase_add_test(tc1_1, sprintf_c_11);
  tcase_add_test(tc1_1, sprintf_c_12);
  tcase_add_test(tc1_1, sprintf_d_1);
  tcase_add_test(tc1_1, sprintf_d_2);
  tcase_add_test(tc1_1, sprintf_d_3);
  tcase_add_test(tc1_1, sprintf_d_4);
  tcase_add_test(tc1_1, sprintf_d_5);
  tcase_add_test(tc1_1, sprintf_d_6);
  tcase_add_test(tc1_1, sprintf_d_7);
  tcase_add_test(tc1_1, sprintf_d_8);
  tcase_add_test(tc1_1, sprintf_d_9);
  tcase_add_test(tc1_1, sprintf_d_10);
  tcase_add_test(tc1_1, sprintf_d_12);
  tcase_add_test(tc1_1, sprintf_d_13);
  tcase_add_test(tc1_1, sprintf_d_14);
  tcase_add_test(tc1_1, sprintf_d_15);
  tcase_add_test(tc1_1, sprintf_d_16);
  tcase_add_test(tc1_1, sprintf_d_17);
  tcase_add_test(tc1_1, sprintf_d_18);
  tcase_add_test(tc1_1, sprintf_d_19);
  tcase_add_test(tc1_1, sprintf_d_20);
  tcase_add_test(tc1_1, sprintf_d_21);
  tcase_add_test(tc1_1, sprintf_d_22);
  tcase_add_test(tc1_1, sprintf_d_23);
  tcase_add_test(tc1_1, sprintf_d_24);
  tcase_add_test(tc1_1, sprintf_d_25);
  tcase_add_test(tc1_1, sprintf_d_26);
  tcase_add_test(tc1_1, sprintf_d_27);
  tcase_add_test(tc1_1, sprintf_d_28);
  tcase_add_test(tc1_1, sprintf_d_29);
  tcase_add_test(tc1_1, sprintf_d_30);
  tcase_add_test(tc1_1, sprintf_d_31);
  tcase_add_test(tc1_1, sprintf_d_32);
  tcase_add_test(tc1_1, sprintf_d_33);
  tcase_add_test(tc1_1, sprintf_d_34);
  tcase_add_test(tc1_1, sprintf_d_35);
  tcase_add_test(tc1_1, sprintf_d_36);
  tcase_add_test(tc1_1, sprintf_d_37);
  tcase_add_test(tc1_1, sprintf_d_38);
  tcase_add_test(tc1_1, sprintf_d_39);
  tcase_add_test(tc1_1, sprintf_d_40);
  tcase_add_test(tc1_1, sprintf_d_41);
  tcase_add_test(tc1_1, sprintf_d_42);
  tcase_add_test(tc1_1, sprintf_d_43);
  tcase_add_test(tc1_1, sprintf_d_44);
  tcase_add_test(tc1_1, sprintf_d_45);
  tcase_add_test(tc1_1, sprintf_d_46);
  tcase_add_test(tc1_1, sprintf_d_47);
  tcase_add_test(tc1_1, sprintf_d_48);
  tcase_add_test(tc1_1, sprintf_d_49);
  tcase_add_test(tc1_1, sprintf_d_50);
  tcase_add_test(tc1_1, sprintf_d_51);
  tcase_add_test(tc1_1, sprintf_d_52);
  tcase_add_test(tc1_1, sprintf_d_53);
  tcase_add_test(tc1_1, sprintf_d_54);
  tcase_add_test(tc1_1, sprintf_d_55);
  tcase_add_test(tc1_1, sprintf_d_56);
  tcase_add_test(tc1_1, sprintf_d_57);
  tcase_add_test(tc1_1, sprintf_s_1);
  tcase_add_test(tc1_1, sprintf_s_2);
  tcase_add_test(tc1_1, sprintf_s_3);
  tcase_add_test(tc1_1, sprintf_s_4);
  tcase_add_test(tc1_1, sprintf_s_5);
  tcase_add_test(tc1_1, sprintf_s_6);
  tcase_add_test(tc1_1, sprintf_s_7);
  tcase_add_test(tc1_1, sprintf_s_8);
  tcase_add_test(tc1_1, sprintf_s_9);
  tcase_add_test(tc1_1, sprintf_s_10);
  tcase_add_test(tc1_1, sprintf_s_11);
  tcase_add_test(tc1_1, sprintf_s_12);
  tcase_add_test(tc1_1, sprintf_s_13);
  tcase_add_test(tc1_1, sprintf_s_14);
  tcase_add_test(tc1_1, sprintf_s_15);
  tcase_add_test(tc1_1, sprintf_s_16);
  tcase_add_test(tc1_1, sprintf_s_17);
  tcase_add_test(tc1_1, sprintf_s_18);
  tcase_add_test(tc1_1, sprintf_s_19);
  tcase_add_test(tc1_1, sprintf_s_20);
  tcase_add_test(tc1_1, sprintf_f_1);
  tcase_add_test(tc1_1, sprintf_f_2);
  tcase_add_test(tc1_1, sprintf_f_3);
  tcase_add_test(tc1_1, sprintf_f_4);
  tcase_add_test(tc1_1, sprintf_f_5);
  tcase_add_test(tc1_1, sprintf_f_6);
  tcase_add_test(tc1_1, sprintf_f_7);
  tcase_add_test(tc1_1, sprintf_f_8);
  tcase_add_test(tc1_1, sprintf_f_9);
  tcase_add_test(tc1_1, sprintf_f_10);
  tcase_add_test(tc1_1, sprintf_f_11);
  tcase_add_test(tc1_1, sprintf_f_12);
  tcase_add_test(tc1_1, sprintf_f_13);
  tcase_add_test(tc1_1, sprintf_f_14);
  tcase_add_test(tc1_1, sprintf_f_15);
  tcase_add_test(tc1_1, sprintf_f_16);
  tcase_add_test(tc1_1, sprintf_f_17);
  tcase_add_test(tc1_1, sprintf_f_18);
  tcase_add_test(tc1_1, sprintf_f_19);
  tcase_add_test(tc1_1, sprintf_f_20);
  tcase_add_test(tc1_1, sprintf_f_21);
  tcase_add_test(tc1_1, sprintf_f_22);
  tcase_add_test(tc1_1, sprintf_f_23);
  tcase_add_test(tc1_1, sprintf_f_24);
  tcase_add_test(tc1_1, sprintf_f_25);
  tcase_add_test(tc1_1, sprintf_f_26);
  tcase_add_test(tc1_1, sprintf_f_27);
  tcase_add_test(tc1_1, sprintf_f_28);
  tcase_add_test(tc1_1, sprintf_f_29);
  tcase_add_test(tc1_1, sprintf_f_30);
  tcase_add_test(tc1_1, sprintf_f_31);
  tcase_add_test(tc1_1, sprintf_f_32);
  tcase_add_test(tc1_1, sprintf_f_33);
  tcase_add_test(tc1_1, sprintf_f_34);
  tcase_add_test(tc1_1, sprintf_f_35);
  tcase_add_test(tc1_1, sprintf_f_36);
  tcase_add_test(tc1_1, sprintf_f_37);
  tcase_add_test(tc1_1, sprintf_f_38);
  tcase_add_test(tc1_1, sprintf_f_39);
  tcase_add_test(tc1_1, sprintf_f_40);
  tcase_add_test(tc1_1, sprintf_f_41);
  tcase_add_test(tc1_1, sprintf_f_42);
  tcase_add_test(tc1_1, sprintf_f_43);
  tcase_add_test(tc1_1, sprintf_f_44);
  tcase_add_test(tc1_1, sprintf_f_45);
  tcase_add_test(tc1_1, sprintf_f_46);
  tcase_add_test(tc1_1, sprintf_f_47);
  tcase_add_test(tc1_1, sprintf_f_48);
  tcase_add_test(tc1_1, sprintf_f_49);
  tcase_add_test(tc1_1, sprintf_f_50);
  tcase_add_test(tc1_1, sprintf_p_1);
  tcase_add_test(tc1_1, sprintf_p_2);
  tcase_add_test(tc1_1, sprintf_p_3);
  tcase_add_test(tc1_1, sprintf_p_4);
  tcase_add_test(tc1_1, sprintf_p_5);
  tcase_add_test(tc1_1, sprintf_p_6);
  tcase_add_test(tc1_1, sprintf_p_7);
  tcase_add_test(tc1_1, sprintf_p_8);
  tcase_add_test(tc1_1, sprintf_u_1);
  tcase_add_test(tc1_1, sprintf_u_2);
  tcase_add_test(tc1_1, sprintf_u_3);
  tcase_add_test(tc1_1, sprintf_u_4);
  tcase_add_test(tc1_1, sprintf_u_5);
  tcase_add_test(tc1_1, sprintf_u_6);
  tcase_add_test(tc1_1, sprintf_u_7);
  tcase_add_test(tc1_1, sprintf_u_8);
  tcase_add_test(tc1_1, sprintf_u_9);
  tcase_add_test(tc1_1, sprintf_u_10);
  tcase_add_test(tc1_1, sprintf_u_11);
  tcase_add_test(tc1_1, sprintf_u_12);
  tcase_add_test(tc1_1, sprintf_u_13);
  tcase_add_test(tc1_1, sprintf_u_14);
  tcase_add_test(tc1_1, sprintf_u_15);
  tcase_add_test(tc1_1, sprintf_u_16);
  tcase_add_test(tc1_1, sprintf_u_17);
  tcase_add_test(tc1_1, sprintf_u_18);
  tcase_add_test(tc1_1, sprintf_u_19);
  tcase_add_test(tc1_1, sprintf_u_20);
  tcase_add_test(tc1_1, sprintf_u_21);
  tcase_add_test(tc1_1, sprintf_u_22);
  tcase_add_test(tc1_1, sprintf_u_23);
  tcase_add_test(tc1_1, sprintf_u_24);
  tcase_add_test(tc1_1, sprintf_u_25);
  tcase_add_test(tc1_1, sprintf_u_26);
  tcase_add_test(tc1_1, sprintf_u_27);
  tcase_add_test(tc1_1, sprintf_u_28);
  tcase_add_test(tc1_1, sprintf_u_29);
  tcase_add_test(tc1_1, sprintf_u_30);
  tcase_add_test(tc1_1, sprintf_u_31);
  tcase_add_test(tc1_1, sprintf_u_32);
  tcase_add_test(tc1_1, sprintf_u_33);
  tcase_add_test(tc1_1, sprintf_u_34);
  tcase_add_test(tc1_1, sprintf_u_35);
  tcase_add_test(tc1_1, sprintf_u_36);
  tcase_add_test(tc1_1, sprintf_u_37);
  tcase_add_test(tc1_1, sprintf_u_38);
  tcase_add_test(tc1_1, sprintf_u_39);
  tcase_add_test(tc1_1, sprintf_u_40);
  tcase_add_test(tc1_1, sprintf_u_41);
  tcase_add_test(tc1_1, sprintf_u_42);
  tcase_add_test(tc1_1, sprintf_u_43);
  tcase_add_test(tc1_1, sprintf_u_44);
  tcase_add_test(tc1_1, sprintf_u_45);
  tcase_add_test(tc1_1, sprintf_u_46);
  tcase_add_test(tc1_1, sprintf_u_47);
  tcase_add_test(tc1_1, sprintf_u_48);
  tcase_add_test(tc1_1, sprintf_u_49);
  tcase_add_test(tc1_1, sprintf_u_50);
  tcase_add_test(tc1_1, sprintf_u_51);
  tcase_add_test(tc1_1, sprintf_u_52);
  tcase_add_test(tc1_1, sprintf_u_53);
  tcase_add_test(tc1_1, sprintf_u_54);
  tcase_add_test(tc1_1, sprintf_o_1);
  tcase_add_test(tc1_1, sprintf_o_2);
  tcase_add_test(tc1_1, sprintf_o_3);
  tcase_add_test(tc1_1, sprintf_o_4);
  tcase_add_test(tc1_1, sprintf_o_5);
  tcase_add_test(tc1_1, sprintf_o_6);
  tcase_add_test(tc1_1, sprintf_o_7);
  tcase_add_test(tc1_1, sprintf_o_8);
  tcase_add_test(tc1_1, sprintf_o_9);
  tcase_add_test(tc1_1, sprintf_o_10);
  tcase_add_test(tc1_1, sprintf_o_11);
  tcase_add_test(tc1_1, sprintf_o_12);
  tcase_add_test(tc1_1, sprintf_o_13);
  tcase_add_test(tc1_1, sprintf_o_14);
  tcase_add_test(tc1_1, sprintf_o_15);
  tcase_add_test(tc1_1, sprintf_o_16);
  tcase_add_test(tc1_1, sprintf_o_17);
  tcase_add_test(tc1_1, sprintf_o_18);
  tcase_add_test(tc1_1, sprintf_o_19);
  tcase_add_test(tc1_1, sprintf_o_20);
  tcase_add_test(tc1_1, sprintf_x_1);
  tcase_add_test(tc1_1, sprintf_x_2);
  tcase_add_test(tc1_1, sprintf_x_3);
  tcase_add_test(tc1_1, sprintf_x_4);
  tcase_add_test(tc1_1, sprintf_x_5);
  tcase_add_test(tc1_1, sprintf_x_6);
  tcase_add_test(tc1_1, sprintf_x_7);
  tcase_add_test(tc1_1, sprintf_x_8);
  tcase_add_test(tc1_1, sprintf_x_9);
  tcase_add_test(tc1_1, sprintf_x_10);
  tcase_add_test(tc1_1, sprintf_x_11);
  tcase_add_test(tc1_1, sprintf_x_12);
  tcase_add_test(tc1_1, sprintf_x_13);
  tcase_add_test(tc1_1, sprintf_x_14);
  tcase_add_test(tc1_1, sprintf_x_15);
  tcase_add_test(tc1_1, sprintf_x_16);
  tcase_add_test(tc1_1, sprintf_x_17);
  tcase_add_test(tc1_1, sprintf_x_18);
  tcase_add_test(tc1_1, sprintf_x_19);
  tcase_add_test(tc1_1, sprintf_x_20);
  tcase_add_test(tc1_1, sprintf_e_1);
  tcase_add_test(tc1_1, sprintf_e_2);
  tcase_add_test(tc1_1, sprintf_e_3);
  tcase_add_test(tc1_1, sprintf_e_4);
  tcase_add_test(tc1_1, sprintf_e_5);
  tcase_add_test(tc1_1, sprintf_e_6);
  tcase_add_test(tc1_1, sprintf_e_7);
  tcase_add_test(tc1_1, sprintf_e_8);
  tcase_add_test(tc1_1, sprintf_e_9);
  tcase_add_test(tc1_1, sprintf_e_10);
  tcase_add_test(tc1_1, sprintf_e_11);
  tcase_add_test(tc1_1, sprintf_e_12);
  tcase_add_test(tc1_1, sprintf_e_13);
  tcase_add_test(tc1_1, sprintf_e_14);
  tcase_add_test(tc1_1, sprintf_e_15);
  tcase_add_test(tc1_1, sprintf_e_16);
  tcase_add_test(tc1_1, sprintf_e_17);
  tcase_add_test(tc1_1, sprintf_e_18);
  tcase_add_test(tc1_1, sprintf_e_19);
  tcase_add_test(tc1_1, sprintf_e_20);
  tcase_add_test(tc1_1, sprintf_e_21);
  tcase_add_test(tc1_1, sprintf_e_22);
  tcase_add_test(tc1_1, sprintf_e_23);
  tcase_add_test(tc1_1, sprintf_e_24);
  tcase_add_test(tc1_1, sprintf_e_25);
  tcase_add_test(tc1_1, sprintf_e_26);
  tcase_add_test(tc1_1, sprintf_e_27);
  tcase_add_test(tc1_1, sprintf_e_28);
  tcase_add_test(tc1_1, sprintf_e_29);
  tcase_add_test(tc1_1, sprintf_e_30);
  tcase_add_test(tc1_1, sprintf_g);
  tcase_add_test(tc1_1, sprintf_empty);
  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}